config/routes.rb
Rails.application.routes.draw do

  resources :questions
  resources :tags
  resources :filters
  resources :users

  root 'welcome_page#index'

  get 'signup' => 'welcome_page#signup'

  get 'users/index'

  get 'login' => 'session#index'

  get 'session/new'

  post 'login' => 'session#create'

  post 'show' => 'questions#show'

  get 'outgoing' => 'questions#outgoing'
  get 'incoming' => 'questions#incoming'

  get 'ask' => 'questions#new'
 
  delete 'logout' => 'session#destroy'

end

app/models/question.rb
class Question < ActiveRecord::Base

	validates :description, presence: true, length: {maximum: 250}

	has_many :answers
	has_many :filters
	belongs_to :user
	has_many :tags

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  def outgoing
    @questions = Question.where("user_id = ?", current_user.id)
    index = 0
    @ids = []
    @questions.each do |q|
      index += 1
      @ids << q.id
    end

    # record each answer
    @ids.each do |i|
      if (params[i.to_s] != "")
        a = Answer.new
        a.description = params[i.to_s]
        a.question_id = i.to_s
        a.user_id = current_user.id
        a.save
      end
    end
  end

  def incoming
    @questions = Question.where("user_id = ?", current_user.id)
    index = 0
    @ids = []
    @questions.each do |q|
      index += 1
      @ids << q.id
    end

    @ids.each do |i|
      if (params[i.to_s] != "")
        a = Answer.new
        a.description = params[i.to_s]
        a.question_id = i.to_s
        a.user_id = current_user.id
        a.save
      end
    end
  end

  # GET /questions/new
  def new
    @age_filter = Filter.where("ftype = ?", "AGE").order("subtype")
    @gender_filter = Filter.where("ftype = ?", "GENDER").order("subtype")
    @race_filter = Filter.where("ftype = ?", "RACE").order("subtype")
    @smoking_filter = Filter.where("ftype = ?", "SMOKING STATUS").order("subtype")
    @immu_filter = Filter.where("ftype = ?", "IMMUNOCOMPROMISED").order("subtype")
    @renal_filter = Filter.where("ftype = ?", "RENAL IMPAIRMENT").order("subtype")
    @preg_filter = Filter.where("ftype = ?", "PREGNANCY").order("subtype")
    @tags = Tag.all
    @question = Question.new
    if (params[:question] != nil) 

      q = Question.new
      q.description = params[:question]
      q.age = params[:age]
      q.gender = params[:gender]
      q.race = params[:race]
      q.smoking_status = params[:smoking]
      q.immunocompromised = params[:immu]
      q.renal_impairment = params[:renal]
      q.pregnancy = params[:preg]
      q.user = current_user
      q.save

      redirect_to "/outgoing"

    else
    end
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:description, :age, :gender, :race, :smoking_status, :immunocompromised, :renal_impairment, :pregnancy, :tag)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :race %><br>
    <%= f.text_field :race %>
  </div>
  <div class="field">
    <%= f.label :smoking_status %><br>
    <%= f.text_field :smoking_status %>
  </div>
  <div class="field">
    <%= f.label :immunocompromised %><br>
    <%= f.text_field :immunocompromised %>
  </div>
  <div class="field">
    <%= f.label :renal_impairment %><br>
    <%= f.text_field :renal_impairment %>
  </div>
  <div class="field">
    <%= f.label :pregnancy %><br>
    <%= f.text_field :pregnancy %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/incoming.html.erb
<% if (@questions.count == 0) %>
	<h>There is no questions for you</h>
<% else %>
<form>
	<% index = 0 %>
	<div class="panel-group" id="accordion">
	<% @questions.each do |q| %>
		<div class="panel panel-default">
			<div class="panel-heading">
      			<h4 class="panel-title">
        			<a data-toggle="collapse" data-parent="#accordion" href="#<%= index.to_s %>">Q<%= (index + 1).to_s %></a>
      			</h4>
    		</div>
			<div id="<%= index.to_s %>" class="panel-collapse collapse in">
				<i><b><div class="jumbotron"><%= q.description %></b></i>
				<br><% if q.age != "" %>
					<b>Age:</b><%= q.age %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.gender != "" %>
					<b>Gender:</b><%= q.gender %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.race != "" %>
					<b>Race:</b><%= q.race %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.smoking_status != "" %>
					<b>Smoking Status:</b><%= q.smoking_status %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.immunocompromised != "" %>
					<b>Immunocompromised:</b><%= q.immunocompromised %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.renal_impairment != "" %>
					<b>Renal Impairment:</b><%= q.renal_impairment %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.pregnancy != "" %>
					<b>Pregnancy:</b><%= q.pregnancy %>
				<% end %>
				<br><div class="text-right">
					Created at <%= q.created_at.in_time_zone('Eastern Time (US & Canada)').to_s[0, 19] %>
				</div>

				<!-- answers are here -->
				<% answers = Answer.where("question_id = ?", q.id) %>
				<% if (answers.count != 0) %>
					<br><div class="text-center">
						<p><b>Answers</b></p>
					</div>
					<% answers.each do |answer| %>
						<b><%= User.where("id = ?", answer.user_id).take.username %>: </b>
						<b><i><%= answer.description %></i></b>
						<br>
					<% end %>
				<% end %>

				<div class="text-center">
					<br><p><b>Post your answer here</b></p>
				</div>
				<%= text_area_tag(@ids[index].to_s, "", size: "24x12") %>
			</div>

			<% index += 1 %>
		</div>
	</div>
	<% end %> 
	<br><div class="text-center">
		<button type="submit" class="btn btn-success btn-lg">Submit</button>
	</div>
</form>
<% end %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Race</th>
      <th>Smoking status</th>
      <th>Immunocompromised</th>
      <th>Renal impairment</th>
      <th>Pregnancy</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.description %></td>
        <td><%= question.age %></td>
        <td><%= question.gender %></td>
        <td><%= question.race %></td>
        <td><%= question.smoking_status %></td>
        <td><%= question.immunocompromised %></td>
        <td><%= question.renal_impairment %></td>
        <td><%= question.pregnancy %></td>
        <td><%= question.tag %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<% provide(:title, "Asking") %>

<form>
<div class="jumbotron">

	<div class="container-fluid">
		<div class="form-group">
 	 		<label for="question">Post your questions here</label>
  			<%= text_area_tag(:question, "", size: "24x12") %>
		</div>
	</div>

	<div class="container-fluid">
		<div class="row">

			<div class="col-xs-4">
				<div class="form-group">
					
					<label for="age">AGE</label>
					<%= select_tag :age, options_from_collection_for_select(@age_filter, 'subtype', 'subtype') %>

					
				</div>
			</div>

			<div class="col-xs-4">
				<div class="form-group">
					<label for="gender">GENDER</label>
					<%= select_tag :gender, options_from_collection_for_select(@gender_filter, 'subtype', 'subtype') %>

				</div>
			</div>

			<div class="col-xs-4">
				<div class="form-group">
					<label for="race">RACE</label>
					<%= select_tag :race, options_from_collection_for_select(@race_filter, 'subtype', 'subtype') %>

				</div>
			</div>

			<div class="col-xs-4">
				<div class="form-group">
					<label for="smoking">SMOKING STATUS</label>
					<%= select_tag :smoking, options_from_collection_for_select(@smoking_filter, 'subtype', 'subtype') %>

				</div>
			</div>

			<div class="col-xs-4">
				<div class="form-group">
					<label for="immu">IMMUNOCOMPROMISED</label>
					<%= select_tag :immu, options_from_collection_for_select(@immu_filter, 'subtype', 'subtype') %>

				</div>
			</div>

			<div class="col-xs-4">
				<div class="form-group">
					<label for="renal">RENAL IMPAIRMENT</label>
					<%= select_tag :renal, options_from_collection_for_select(@renal_filter, 'subtype', 'subtype') %>

				</div>
			</div>

			<div class="col-xs-4">
				<div class="form-group">
					<label for="preg">PREGNANCY</label>
					<%= select_tag :preg, options_from_collection_for_select(@preg_filter, 'subtype', 'subtype') %>

				</div>
			</div>

			<!--<div class="col-xs-4">
				<div class="form-group">
					<label for="tag">TAG</label>
					<select class="form-control" id="tag">
						<% @tags.each do |tag| %>
							<option><%= tag.name %></option>
						<% end %>
					</select>
				</div>
			</div> -->
 

			
		</div>
	</div>
	

	<div class="container-fluid">
		<label>Which pool(s) would you like to send?</label>
		<br><input type="text" value="Heart Disease, Obesity" data-role="tagsinput" />
<script>
var citynames = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace,
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  prefetch: {
    url: '/json/tags.json',
    filter: function(list) {
      return $.map(list, function(cityname) {
        return { name: cityname }; });
    }
  }
});
citynames.initialize();

$('input').tagsinput({
  typeaheadjs: {
    name: 'citynames',
    displayKey: 'name',
    valueKey: 'name',
    source: citynames.ttAdapter()
  }
});

</script>
	</div>
</div>


<div class="text-center">
	<button type="submit" class="btn btn-success btn-lg">Submit</button>
</div>
</form>

app/views/questions/outgoing.html.erb
<% if (@questions.count == 0) %>
	<p>You have not asked any question</p>
<% else %>

<form>
	<% index = 0 %>
	<div class="panel-group" id="accordion">
	<% @questions.each do |q| %>
		<div class="panel panel-default">
			<div class="panel-heading">
      			<h4 class="panel-title">
        			<a data-toggle="collapse" data-parent="#accordion" href="#<%= index.to_s %>">Q<%= (index + 1).to_s %></a>
      			</h4>
    		</div>
			<div id="<%= index.to_s %>" class="panel-collapse collapse in">
				<i><b><div class="jumbotron"><%= q.description %></b></i>
				<br><% if q.age != "" %>
					<b>Age:</b><%= q.age %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.gender != "" %>
					<b>Gender:</b><%= q.gender %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.race != "" %>
					<b>Race:</b><%= q.race %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.smoking_status != "" %>
					<b>Smoking Status:</b><%= q.smoking_status %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.immunocompromised != "" %>
					<b>Immunocompromised:</b><%= q.immunocompromised %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.renal_impairment != "" %>
					<b>Renal Impairment:</b><%= q.renal_impairment %>&nbsp;&nbsp;&nbsp;
				<% end %>

				<% if q.pregnancy != "" %>
					<b>Pregnancy:</b><%= q.pregnancy %>
				<% end %>
				<br><div class="text-right">
					Created at <%= q.created_at.in_time_zone('Eastern Time (US & Canada)').to_s[0, 19] %>
				</div>

				<!-- answers are here -->
				<% answers = Answer.where("question_id = ?", q.id) %>
				<% if (answers.count != 0) %>
					<br><div class="text-center">
						<p><b>Answers</b></p>
					</div>
					<% answers.each do |answer| %>
						<b><%= User.where("id = ?", answer.user_id).take.username %>: </b>
						<b><i><%= answer.description %></i></b>
						<br>
					<% end %>
				<% end %>

				<div class="text-center">
					<br><p><b>Post your answer here</b></p>
				</div>
				<%= text_area_tag(@ids[index].to_s, "", size: "24x12") %>
			</div>

			<% index += 1 %>
		</div>
	</div>
	<% end %> 
	<br><div class="text-center">
		<button type="submit" class="btn btn-success btn-lg">Submit</button>
	</div>
</form>
<% end %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>

<p>
  <strong>Age:</strong>
  <%= @question.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @question.gender %>
</p>

<p>
  <strong>Race:</strong>
  <%= @question.race %>
</p>

<p>
  <strong>Smoking status:</strong>
  <%= @question.smoking_status %>
</p>

<p>
  <strong>Immunocompromised:</strong>
  <%= @question.immunocompromised %>
</p>

<p>
  <strong>Renal impairment:</strong>
  <%= @question.renal_impairment %>
</p>

<p>
  <strong>Pregnancy:</strong>
  <%= @question.pregnancy %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @question.tag %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>