config/routes.rb
Rails.application.routes.draw do

  resources :questions
  resources :tags
  resources :filters
  resources :users

  root 'welcome_page#index'

  get 'signup' => 'welcome_page#signup'

  get 'users/index'

  get 'login' => 'session#index'

  get 'session/new'

  post 'login' => 'session#create'

  post 'show' => 'questions#show'

  get 'outgoing' => 'questions#outgoing'
  get 'incoming' => 'questions#incoming'

  get 'ask' => 'questions#new'
 
  delete 'logout' => 'session#destroy'

end

app/models/filter.rb
# == Schema Information
#
# Table name: filters
#
#  id         :integer          not null, primary key
#  ftype      :string
#  subtype    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Filter < ActiveRecord::Base
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_action :set_filter, only: [:show, :edit, :update, :destroy]

  # GET /filters
  # GET /filters.json
  def index
    @filters = Filter.all
  end

  # GET /filters/1
  # GET /filters/1.json
  def show
  end

  # GET /filters/new
  def new
    @filter = Filter.new
  end

  # GET /filters/1/edit
  def edit
  end

  # POST /filters
  # POST /filters.json
  def create
    @filter = Filter.new(filter_params)

    respond_to do |format|
      if @filter.save
        format.html { redirect_to @filter, notice: 'Filter was successfully created.' }
        format.json { render :show, status: :created, location: @filter }
      else
        format.html { render :new }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filters/1
  # PATCH/PUT /filters/1.json
  def update
    respond_to do |format|
      if @filter.update(filter_params)
        format.html { redirect_to @filter, notice: 'Filter was successfully updated.' }
        format.json { render :show, status: :ok, location: @filter }
      else
        format.html { render :edit }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filters/1
  # DELETE /filters/1.json
  def destroy
    @filter.destroy
    respond_to do |format|
      format.html { redirect_to filters_url, notice: 'Filter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filter
      @filter = Filter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filter_params
      params.require(:filter).permit(:ftype, :subtype)
    end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_form.html.erb
<%= form_for(@filter) do |f| %>
  <% if @filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

      <ul>
      <% @filter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ftype %><br>
    <%= f.text_field :ftype %>
  </div>
  <div class="field">
    <%= f.label :subtype %><br>
    <%= f.text_field :subtype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filters/edit.html.erb
<h1>Editing Filter</h1>

<%= render 'form' %>

<%= link_to 'Show', @filter %> |
<%= link_to 'Back', filters_path %>

app/views/filters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Filters</h1>

<table>
  <thead>
    <tr>
      <th>Ftype</th>
      <th>Subtype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @filters.each do |filter| %>
      <tr>
        <td><%= filter.ftype %></td>
        <td><%= filter.subtype %></td>
        <td><%= link_to 'Show', filter %></td>
        <td><%= link_to 'Edit', edit_filter_path(filter) %></td>
        <td><%= link_to 'Destroy', filter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Filter', new_filter_path %>

app/views/filters/new.html.erb
<h1>New Filter</h1>

<%= render 'form' %>

<%= link_to 'Back', filters_path %>

app/views/filters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ftype:</strong>
  <%= @filter.ftype %>
</p>

<p>
  <strong>Subtype:</strong>
  <%= @filter.subtype %>
</p>

<%= link_to 'Edit', edit_filter_path(@filter) %> |
<%= link_to 'Back', filters_path %>